// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag (manually reconstructed).
package docs

import "github.com/swaggo/swag"

// docTemplate defines the base Swagger 2.0 template.
// The real paths, parameters and responses are filled in by swag based on annotations.
const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "CYP-Registry 技术支持",
            "email": "nasDSSCYP@outlook.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        {{range $key, $value := .Paths}}
        "{{$key}}": {
            {{range $method, $item := $value}}
            "{{$method}}": {
                "tags": [{{range $i, $tag := $item.Tags}}{{if $i}}, {{end}}"{{$tag}}"{{end}}],
                "summary": "{{$item.Summary}}",
                "description": "{{$item.Description}}",
                "operationId": "{{$item.OperationID}}",
                "parameters": [
                    {{range $i, $param := $item.Parameters}}
                    {{if $i}},{{end}}
                    {
                        "name": "{{$param.Name}}",
                        "in": "{{$param.In}}",
                        "description": "{{$param.Description}}",
                        "required": {{$param.Required}},
                        "type": "{{$param.Type}}"
                    }
                    {{end}}
                ],
                "responses": {
                    {{range $i, $resp := $item.Responses}}
                    {{if $i}},{{end}}
                    "{{$resp.Code}}": {
                        "description": "{{$resp.Description}}"
                    }
                    {{end}}
                }
            }
            {{end}}
        }
        {{end}}
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "Bearer": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Title:            "CYP-Registry API",
	Description:      "CYP-Registry Container Registry Management API",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

// init registers the SwaggerInfo so swag.ReadDoc can return
// the fully generated OpenAPI document (including annotated routes).
func init() {
	swag.Register(swag.Name, SwaggerInfo)
}

