run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  # typecheck 已通过 linters.disable-all + enable 列表排除（不在列表中即被禁用）
  # 即使升级到 v1.60.1+，typecheck 仍可能因依赖解析问题产生误报
  # 由于 go build 已完成类型检查，typecheck 属于冗余检查，直接禁用即可
  govet:
    # 注意：check-shadowing 已废弃，如需检查变量遮蔽，请在 linters.enable 中添加 shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - lll
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - gosec
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gomodguard
    - goprintffuncname
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - whitespace
    - shadow  # 检查变量遮蔽（替代已废弃的 govet.check-shadowing）
  # typecheck 已通过 disable-all + enable 列表排除（不在列表中即被禁用）
  # 如果依赖正确下载，可以启用 typecheck 进行更严格的类型检查
  # 如需启用 typecheck，将其添加到 enable 列表即可

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - gocyclo
        - dupl
        - lll
    - path: cmd/
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # 如果依赖正确下载，typecheck 应该能正常工作
    # 如果仍然出现 typecheck 错误，说明依赖未正确下载，应检查 CI 配置
    # 以下规则作为兜底措施，过滤可能的 typecheck 错误
    - ".* \\(typecheck\\)$"
    - ".*undefined:.*\\(typecheck\\)"
    - "Error:.*\\(typecheck\\)"
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|.*println).* is not checked"
    - "exported function .* should have comment or be unexported"
    - "package comment should be of the form"
    - "comment on exported (function|method|type|const|var) .* should be"
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "don't use an underscore in package name"
    - "var.*is unused"
    - "func.*is unused"
    - "type.*is unused"
    - "const.*is unused"
    - "comment on exported.*"
    - "should have comment"
    - "should not use dot imports"
    - "should have comment or be unexported"
    - "Error return value of .* is not checked"
    - "G104: Errors unhandled"
    - "G204: Subprocess launched.*should be audited"
    - "G401: Use of weak cryptographic primitive"
    - "G402: TLS InsecureSkipVerify set true"
    - "G404: Use of weak random number generator"
    - "G501: Import block to be grouped"
    - "G601: Implicit memory aliasing in for loop"
